#version: '3.9'
services:
  hyperf-skeleton:
    container_name: hyperf
    image: hyperf
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 80:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

networks:
  default:
    name: hyperf
